version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0  # travamento em versão específica anti code breaker
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0       # Versão específica do Kafka
    depends_on:
      - zookeeper # Depende que o zookeeper esteja rodando
    ports:
      - "9092:9092" #localhost access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://0.0.0.0:9092 # porta do kafdrop
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 #single node setup

  mongo: #mantém os registros dos containers
    image: mongo:latest 
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000" #localhost:9000 web access
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092" # internal kafka containers address
      JVM_OPTS: "-Xms16M -Xmx64M" #limita o uso de memória do kafdrop
      SERVER_SERVLET_CONTEXTPATH: "/"

volumes:
  mongo-data: #mantém os registros dos containers
